Repository monadicus/snarkops, pull requests merged in 2024-09, with the labels that each got.

#259 feat: increased cannon reliability
  crates/aot/src/runner/mod.rs
  crates/aot/src/runner/rpc/mod.rs
  crates/aot/src/runner/rpc/node.rs
  crates/snops-agent/src/cli.rs
  crates/snops-agent/src/rpc/agent.rs
  crates/snops-agent/src/rpc/control.rs
  crates/snops-cli/src/commands/agent.rs
  crates/snops-common/src/aot_cmds/authorization.rs
  crates/snops-common/src/aot_cmds/mod.rs
  crates/snops-common/src/format/impl_chrono.rs
  crates/snops-common/src/format/impl_json.rs
  crates/snops-common/src/format/mod.rs
  crates/snops-common/src/rpc/agent/node.rs
  crates/snops-common/src/rpc/control/agent.rs
  crates/snops-common/src/rpc/control/mod.rs
  crates/snops-common/src/rpc/error.rs
  crates/snops-common/src/state/agent_status.rs
  crates/snops-common/src/state/snarkos_status.rs
  crates/snops-common/src/util.rs
  crates/snops/src/cannon/context.rs
  crates/snops/src/cannon/error.rs
  crates/snops/src/cannon/mod.rs
  crates/snops/src/cannon/router.rs
  crates/snops/src/cannon/sink.rs
  crates/snops/src/cannon/source.rs
  crates/snops/src/cannon/status.rs
  crates/snops/src/cannon/tracker.rs
  crates/snops/src/db.rs
  crates/snops/src/env/cache.rs
  crates/snops/src/env/mod.rs
  crates/snops/src/main.rs
  crates/snops/src/persist/env.rs
  crates/snops/src/persist/sink.rs
  crates/snops/src/server/actions/deploy.rs
  crates/snops/src/server/actions/execute.rs
  crates/snops/src/server/api.rs
  crates/snops/src/server/error.rs
  crates/snops/src/server/mod.rs
  crates/snops/src/server/rpc.rs
  crates/snops/src/state/external_peers.rs
  crates/snops/src/state/global.rs
  crates/snops/src/state/mod.rs
  crates/snops/src/state/rpc.rs
  crates/snops/src/state/snarkos_request.rs
  crates/snops/src/state/transactions.rs
  index.html
  scripts/agent.sh
  snops_book/user_guide/clis/SNOPS_CLI.md
  snops_book/user_guide/envs/CANNONS.md
  snops_book/user_guide/envs/STORAGE.md
Labels: feature

#262 Refactor/deprecate cargo make
  Cargo.lock
  Cargo.toml
  Makefile.toml
  crates/snops/src/persist/storage.rs
  crates/snops/src/schema/storage/mod.rs
  crates/xtask/Cargo.toml
  crates/xtask/src/main.rs
Labels: refactor

#263 Chore: update all deps
  .github/workflows/pr.yml
  Cargo.lock
  Cargo.toml
  crates/aot/Cargo.toml
  crates/snops-agent/Cargo.toml
  crates/snops-cli/Cargo.toml
  crates/snops/Cargo.toml
Labels: chore

#283 feat(snops): add private_key, env, and binary config action flags
  Cargo.lock
  crates/snops-agent/src/cli.rs
  crates/snops-agent/src/metrics/mod.rs
  crates/snops-agent/src/rpc/control.rs
  crates/snops-cli/Cargo.toml
  crates/snops-cli/src/commands/env/action/mod.rs
  crates/snops-common/src/action_models.rs
  crates/snops-common/src/state/node_state.rs
  crates/snops/src/server/actions/config.rs
Labels: feature
